-- AlterTable
ALTER TABLE `ProcessingJob` MODIFY `type` ENUM('PROBE', 'FRAME_EXTRACTION', 'AUDIO_EXTRACTION', 'TRANSCRIPTION', 'VISION_ANALYSIS', 'OCR_ANALYSIS', 'COLOR_ANALYSIS', 'SUBJECT_ANALYSIS', 'TRIBE_ANALYSIS', 'SALES_ENGINE', 'PREDICTION', 'RECOMMENDATION') NOT NULL;

-- AlterTable
ALTER TABLE `Video` ADD COLUMN `approvalNotes` TEXT NULL,
    ADD COLUMN `approvalStatus` ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REVISE', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `approvedById` VARCHAR(191) NULL,
    ADD COLUMN `mediaType` ENUM('VIDEO', 'IMAGE', 'AUDIO') NOT NULL DEFAULT 'VIDEO';

-- AlterTable
ALTER TABLE `VideoAnalytics` ADD COLUMN `colourAnalysis` JSON NULL,
    ADD COLUMN `copyAnalysis` JSON NULL,
    ADD COLUMN `salesEngine` JSON NULL,
    ADD COLUMN `sceneAnalysis` JSON NULL,
    ADD COLUMN `subjectAnalysis` JSON NULL,
    ADD COLUMN `unifiedScore` JSON NULL;

-- AddForeignKey
ALTER TABLE `Video` ADD CONSTRAINT `Video_approvedById_fkey` FOREIGN KEY (`approvedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
